#!/bin/bash
# 050302, blb: tar & compress a date-named directory of moved archive log (.arc) files
#	(done separately from move to minimize backup time window)
# 050414, blb: fix "no such dir" error (message) 

# setup
INSTANCE=prod
DESTROOT=/backups/$INSTANCE/arch

# make paths simple for tar
cd $DESTROOT

# bundle 'em up, verify, and if OK: compress and delete the directory
DLIST=`ls -d [0-9][0-9][0-9][0-9][0-9][0-9] 2>>/dev/null` 
for i in $DLIST
do
  echo -n "Archiving ${i}..."
  if /bin/tar -c --verify -f ./archlog_$INSTANCE_$i.tar $i/
  then
    echo -n "Compressing..."
    if /usr/bin/bzip2 $DESTROOT/archlog_$INSTANCE_$i.tar
    then
     echo -n "Cleaning up..."
     rm -R $i
     echo "finished."
    else
      "Directory removal error."
      exit 1
    fi
  else
    echo "BZip2 error."
    exit 1
  fi
done
