#!/bin/bash
# compress dump files in standard /backup directories
# 050122, blb: written
# 050202, blb: limhr, limmin were 05, 00; cd to target dir; better logic for "no matching files"
#		suppress ls's "no files found" to stderr (unwanted cron email)
# 050405, blb: remove arch subdir as target (c.f. archcomprprod)
# 060831, blb: add crp (temporarily)
# 070718, blb: add base
# 090123, blb: remove crp

# start time is determined by cron schedule, these set the latest START time for a compress
LIMHR="04"
LIMMIN="59"

# some basics
BASEDIR=/backups

# for i in prod test sand
for i in prod base
do
  for j in fulldump
  do
    cd $BASEDIR/$i/$j
    FLIST=`ls *[0-9][0-9][0-9] 2>>/dev/null`
    for k in $FLIST
    do
      NOWHR=`date +%H`
      NOWMIN=`date +%M`
      if [ \( "$NOWHR" -le "$LIMHR" \)  -o  \( "$NOWHR" -eq "$LIMHR" -a "$NOWMIN" -lt "$LIMMIN" \) ]
      then
#        printf "Would execute on: %s\n" "$k"
        /usr/bin/bzip2 $k
      fi
    done
  done
done

